/**
 * Each object represents an experience.
 * // Date as string, will be converted to Date in script.js
 */
const ITEMS_DATA = [
    {
        id: 1,
        name: "Starwars Identities",
        description: "An exhibition paying tribute to the universe of George Lucas. Visitors participate in the creation and evolution of an avatar throughout the visit.",
        categories: ["Exhibition"],
        themes: ["Pop-Culture"],
        until: "2015-12-31",
        imageRef: "/images/imex-images/sw1.png",
        altPhotoRef: "images/imex-images/sw0.jpg",
        location: 'Paris',
        creator: 'Les Créations Adonis',
        sections: [
            {
                title: "A bracelet at the heart of the interaction",
                content: "Star Wars Identities is an exhibition paying tribute to the universe of George Lucas. Visitors participate in the creation and evolution of an avatar throughout the visit. With the help of a bracelet, it is possible to make choices at certain moments of the visit: Choice of race, choice of mentor, choices related to our personality, etc... At the end of the visit, our character sheet is presented to us. It is composed of a few images and a text retracing our adventure, all influenced by the choices made during the exhibition",
                imageRef: "/images/imex-images/sw2.png",
                imageCaption: "Bracelet used to identify oneself before each choice"
            },
            {
                title: 'Limited immersion',
                content: "The created avatar cannot be used, I remember being frustrated at not exploiting my character more. The exhibition is very static, you simply look at display cases and screens. Immersion is therefore limited despite the personalization.",
                imageRef: "/images/imex-images/sw4.png",
                imageCaption: "The first choice, that of the race"
            },
            {
                title: 'A first love',
                content: "I was 14 when I went to see the exhibition. The interaction and personalization immediately appealed to me greatly. It is only years later that I realize things could have been pushed further. It should be noted that this interactive exhibition is one of the first in France to work so well. ",
                imageRef: "/images/imex-images/sw3.png",
                imageCaption: "The exhibition logo"
            },
        ],
    },
    {
        id: 2,
        name: "La grotte Cosquer",
        description: "A reconstruction of a famous underwater cave, sheltering traces of prehistoric men and which can be discovered through an immersive visit.",
        categories: ["Exhibition", "Attraction"],
        themes: ["Nature"],
        imageRef: "/images/imex-images/co1.png",
        altPhotoRef: "images/imex-images/co0.jpg",
        location: 'Marseille',
        creator: 'société Kléber Rossillon',
        sections: [
            { title: 'A descent below sea level', 
                content: 'The entrance to the original cave is located 37 meters underwater, due to the Holocene sea level rise, so the experience start by going down in a fake elevator under the sea. Then you install onto the wagons and headphones are given to you for the audio guide. ', 
                imageRef: "/images/imex-images/co4.png", 
                imageCaption: "The relatively famous (and cute) Cosquer Cave penguin" },
            { title: 'Understanding where to look', 
                content: 'The wagons automatically pivot to face the points of interest, thus guiding visitors\' gaze towards the key elements of the exhibition. However, this automation can sometimes give the impression of a lack of control, as visitors cannot freely choose their viewing angle. This reminds me of the scene in Jurassic Park where everyone gets out of the automated car, drawn by a detail, while the car continues its route. It would also have been wise to borrow the flashing highlight behavior from video games to draw the visitor\'s eye to a particular detail. We spend a lot of time looking for the mural painting the audio guide is talking about.',
                imageRef: "/images/imex-images/co3.png", 
                imageCaption: "Wagon pivoting 360 degrees" },
        ],
    },
    {
        id: 3,
        name: "The Soul Station",
        description: "An exhibition at Berghain that addresses and mixes several subjects such as the legacy of colonialism or transidentity through an introspective journey in a video game universe",
        categories: ["Exhibition"],
        themes: ["Art"],
        until: "2024-10-13",
        imageRef: "/images/imex-images/ss1.png",
        altPhotoRef: "images/imex-images/ss0.jpg",
        location: 'Berlin',
        creator: 'Danielle Brathwaite-Shirley',
        sections: [
            { title: 'Let\'s mix PS1, Berghain and spaceship !', 
                content: 'The dark and mysterious atmosphere of Berghain, combined with the retro aesthetic of PS1 horror games, creates a unique atmosphere. This heavy atmosphere fits well with the profound themes addressed (colonialism and transidentity, and all the misfortunes they generate).',
                imageRef: "/images/imex-images/ss5.png", 
                imageCaption: "One of the puzzles, on a very large screen" },
            { title: 'An obscure goal and mechanics', 
                content: 'The goal of the exhibition is to accomplish trials in order to cleanse one\'s soul. These trials are quite obscure and the rules and goals are poorly explained each time. The difficulty is poorly controlled. Indeed, we often find ourselves wandering without really knowing what to do or where to go. This can be frustrating for some visitors who expect a more guided experience. However, it can also be seen as an invitation to exploration and personal discovery, in line with the exhibition\'s themes. In terms of interactions, we are led to interact with tablets, giant screens, button answers, and televisions. The central game, the spaceship, is based on asymmetric gameplay, very fun on paper. The public has information that the pilot does not and must help him navigate. In practice, no one understands.',
                imageRef: "/images/imex-images/ss3.png", 
                imageCaption: "The main attraction, the spaceship with its circular screen" },
            { title: 'A successful sound atmosphere', 
                content: 'The sound atmosphere plays a crucial role in immersion. The background noises add to the dark atmosphere of the place successfully. It is Berghain after all!', 
                imageRef: "/images/imex-images/ss4.png", 
                imageCaption: "A seat, buttons, a screen, choices to make" },

        ],
    },
    {
        hide: true,
        id: 4,
        name: "Odyssée Alpha",
        description: "An artistic experience I contributed to during my final study project for my Master's in Human-Computer Interaction.",
        categories: ["Exhibition",],
        themes: ["Art",],
        until: "2024-03-01",
        imageRef: "/images/imex-images/oa2.png",
        altPhotoRef: "images/imex-images/wip0.jpg",
        location: 'Toulouse',
        creator: 'Maria ',
        sections: [
            { title: 'Section Title 1', 
                content: 'Section content Section content Section content Section content Section content Section content', 
                imageRef: "/images/imex-images/oa1.jpeg", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 2', 
                content: 'Section content Section content Section content Section content Section content', 
                imageRef: "/images/imex-images/oa3.jpeg", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
        ],
    },
    {
        hide: true,
        id: 5,
        name: "Van Gogh : The Immersive Experience",
        description: "An immersive installation including mapping in a church and a VR film.",
        categories: ["Exhibition"],
        themes: ["Art"],
        imageRef: "/images/imex-images/wip1.png",
        altPhotoRef: "images/imex-images/wip0.jpg",
        location: 'Birmingham',
        creator: 'Small Creative',
        sections: [
            { title: 'Section Title 1', 
                content: 'Section content Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip2.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 2', 
                content: 'Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip3.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 3', 
                content: 'Section content Section content Section content Section content Section content',
                imageRef: "/images/wip4.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
        ],
    },
    {
        hide: true,
        id: 6,
        name: "Sons of The Forest",
        description: "Challenge your brain with innovative puzzles in this engaging experience.",
        categories: ["Video Game"],
        themes: ["Nature"],
        imageRef: "/images/imex-images/wip1.png",
        altPhotoRef: "images/imex-images/wip0.jpg",
        location: '/',
        creator: 'Endnight Games',
        sections: [
            { title: 'Section Title 1', 
                content: 'Section content Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip2.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 2', 
                content: 'Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip3.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 3', 
                content: 'Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip4.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
        ],
    },
    {
        hide: true,
        id: 7,
        name: "Free Parties",
        description: "Challenge your brain with innovative puzzles in this engaging experience.",
        categories: ["Activity"],
        themes: ["Nature"],
        imageRef: "/images/imex-images/wip1.png",
        altPhotoRef: "images/imex-images/wip0.jpg",
        location: 'Toulouse',
        creator: 'La guilde d\'Anderexia',
        sections: [
            { title: 'Section Title 1', 
                content: 'Section content Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip2.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 2', 
                content: 'Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip3.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 3', 
                content: 'Section content Section content Section content Section content Section content',
                imageRef: "/images/wip4.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
        ],
    },
    {
        hide: true,
        id: 8,
        name: "Small Creative VR Experiences",
        description: "Challenge your brain with innovative puzzles in this engaging experience.",
        categories: ["Activity"],
        themes: ["Nature"],
        imageRef: "/images/imex-images/wip1.png",
        altPhotoRef: "images/imex-images/wip0.jpg",
        location: 'All over the world',
        creator: 'Small Creative',
        sections: [
            { title: 'Section Title 1', 
                content: 'Section content Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip2.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 2', 
                content: 'Section content Section content Section content Section content Section content', 
                imageRef: "/images/wip3.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
            { title: 'Section Title 3', 
                content: 'Section content Section content Section content Section content Section content',
                imageRef: "/images/wip4.png", 
                imageCaption: "Bracelet used to identify oneself before each choice" },
        ],
    },

];